# Generated by Django 4.1 on 2023-01-17 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "news_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("news_title", models.CharField(blank=True, max_length=512, null=True)),
                ("news_url", models.CharField(blank=True, max_length=512, null=True)),
                ("news_content", models.TextField(blank=True, null=True)),
                ("news_date", models.DateTimeField(blank=True, null=True)),
                ("news_type", models.CharField(blank=True, max_length=50, null=True)),
                ("news_img", models.TextField(blank=True, null=True)),
                ("news_like", models.CharField(blank=True, max_length=50, null=True)),
                ("search_time", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "main_page_newsarticle",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "news_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("comment_content", models.TextField(blank=True, null=True)),
                ("comment_like", models.IntegerField(blank=True, null=True)),
                ("comment_dislike", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "main_page_newscomment",
                "managed": False,
            },
        ),
    ]
